#!/bin/sh

# bash_profile is meant for login invocations.
# macOS conventionally uses a login shell for
# all interactive sessions.

# ::::::::: bashrc :::::::::::::::::::::::::::
[[ -r ~/.bashrc ]] && . ~/.bashrc
