#!/bin/sh

# bash_profile is meant for login invocations.
# macOS conventionally uses a login shell for
# all interactive sessions.

# Sources
files=(~/.bashrc
       ~/.bashrc.local
       ~/.bash_aliases
       ~/.bash_functions)

for file in "${files[@]}"; do
  [ -r "$file" ] && . "$file"
done

# History
export HISTCONTROL=erasedups
export HISTSIZE=10000
shopt -s histappend

# If shell is interactive, disable START/STOP output control.
# This allows Ctrl-S to trigger i-search.
[[ $- = *i* ]] && stty -ixon

# ::::::::: rbenv ::::::::::::::::::::::::::::
if command -v rbenv > /dev/null; then eval "$(rbenv init -)"; fi

