#!/bin/sh

# ::::::::: Preamble :::::::::::::::::::::::::

# bash_profile is meant for login invocations.
# macOS conventionally uses a login shell for
# all interactive sessions.

# ::::::::: Environtment Variables :::::::::::

files=(~/.bashrc
       ~/.bashrc.local
       ~/.bash_aliases
       ~/.bash_functions)

for file in "$files"; do
  [ -r "$file" ] && . "$file"
done

# ::::::::: Options ::::::::::::::::::::::::::

# History
export HISTCONTROL=erasedups
export HISTSIZE=10000
shopt -s histappend

# If the shell is interactive, disable START/STOP output
# control. This allows Ctrl-S to be used for i-search.
case "$-" in
  *i*) stty -ixon;;
esac

# ::::::::: rbenv ::::::::::::::::::::::::::::

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

