#!/bin/sh

# ::::::::: Reload :::::::::::::::::::::::::::
alias r.r=". ~/.bash_profile"

# ::::::::: Git ::::::::::::::::::::::::::::::
alias gst="git status"
alias gpff="git pull --ff-only"
alias gpr="git log origin/master.. --reverse"
alias gpt="git log origin/master.. --reverse --pretty='[\`%h\`](https://github.com/Handybook/handybook/commit/%H) %s'"
alias gpp="git log origin/master.. --reverse -p"
alias gpc="git log origin/master.. -- | wc -l"

# ::::::::: Vim ::::::::::::::::::::::::::::::
alias v=$NEOVIM
alias view="nvim -MR"

# ::::::::: Utils ::::::::::::::::::::::::::::
alias l="CLICOLOR_FORCE=1 ls -lAh"
alias lsa="CLICOLOR_FORCE=1 ls -A"
alias lsf="CLICOLOR_FORCE=1 ls -F"

alias lessr="less -R"

alias cp="cp -iv"
alias mv="mv -iv"

# ::::::::: GDB ::::::::::::::::::::::::::::::
alias gdb="gdb -quiet"

