# bashrc for interactive shells

# bashrc is meant for non-login shells. It should not
# print any output, as that causes tools like scp fail.

# ::::::::: XDG Base Directory :::::::::::::::
{
  # Some well-crafted applications (e.g. git, neovim) observe this spec.
  # https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

  export XDG_CONFIG_HOME="$HOME/.config"
}

# ::::::::: Paths ::::::::::::::::::::::::::::
{
  # PATH
  {
    export SCRIPTS_PATH="$HOME/Development/resources/dotfiles/bin"

    export USR_PATHS="/usr/local:/usr/local/bin:/usr/local/sbin:/usr/bin"

    export PATH="$SCRIPTS_PATH:$USR_PATHS:$PATH"
  }

  # DON'T EXPORT CDPATH, as it can screw up scripts.
  CDPATH=".:~/Development:~/Development/resources:~"

  # Node.js
  export NODE_PATH="/usr/local/lib/node_modules:$NODE_PATH"

  ### Added by the Heroku Toolbelt
  export PATH="/usr/local/heroku/bin:$PATH"
}

# ::::::::: One True Editor(s) :::::::::::::::
{
  # Neovim
  NVIM_TRUE_COLOR="NVIM_TUI_ENABLE_TRUE_COLOR=1 nvim"
  export VISUAL=$NVIM_TRUE_COLOR
  export GIT_EDITOR=$NVIM_TRUE_COLOR
  export SVN_EDITOR=$NVIM_TRUE_COLOR

  # Emacs
  export SPACEMACSDIR="~/Development/resources/emacs/spacemacs.d"
  export EMAIL="ivan.brennan@gmail.com"

  # Configure GNU Global to work with universal-ctags
  export GTAGSCONF=/usr/local/share/gtags/gtags.conf
  export GTAGSLABEL=new-ctags

  # Don't bother editing Git merge commit-messages
  export GIT_MERGE_AUTOEDIT="no"
}

# ::::::::: Bash Completion ::::::::::::::::::
{
  # Activate bash git completion if installed via homebrew
  if [ -f $(brew --prefix >2/dev/null)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
  fi
}

# ::::::::: Colors :::::::::::::::::::::::::::
{
  [ -f ~/.bash_colors.sh ] && . ~/.bash_colors.sh

  if [ -z "$THEME" ]; then
    case "$ITERM_PROFILE" in
      'black'  ) export THEME=dark   ;;
      'remote' ) export THEME=remote ;;
      *        ) export THEME=light  ;;
    esac
  fi

  export CLICOLOR=1
  export GREP_OPTIONS="--color"

  # ls
  {
    # Order of attributes:
    #  1. directory
    #  2. symbolic link
    #  3. socket
    #  4. pipe
    #  5. executable
    #  6. block special
    #  7. character special
    #  8. executable with setuid bit set
    #  9. executable with setgid bit set
    # 10. directory writable to others, with sticky bit
    # 11. directory writable to others, without sticky bit

    # Color designators:
    # a black         A bold black (grey)
    # b red           B bold red
    # c green         C bold green
    # d brown         D bold brown (yellow)
    # e blue          E bold blue
    # f magenta       F bold magenta
    # g cyan          G bold cyan
    # h light grey    H bold light grey (white)
    # x default foreground or background

    # the default is exfxcxdxbxegedabagacad
    export LSCOLORS="exgxcxdxbxegedabagacad"
  }
}

# ::::::::: Prompt :::::::::::::::::::::::::::

  # Git prompt components: {{{1
  minutes_since_last_commit() {
    local now
    local last_commit
    now=`date +%s`
    last_commit=`git log --pretty=format:'%at' -1 2>/dev/null`

    if [ "$?" -eq 0 ]; then
      local seconds_since_last_commit
      local minutes_since_last_commit
      seconds_since_last_commit=$((now-last_commit))
      minutes_since_last_commit=$((seconds_since_last_commit/60))
      echo $minutes_since_last_commit
    fi
  }

  minutes_color() {
    if [ -z "$1" ]; then
      return
    elif [[ "$1" -gt 30 ]]; then
      echo "${RED}"
    elif [[  "$1" -gt 10  ]]; then
      echo "${YELLOW}"
    else
      echo "${GREEN}"
    fi
  }

  grb_git_prompt() {
    local g
    g="$(__gitdir)"

    if [ -n "$g" ]; then
      local COLOR
      local MINUTES_SINCE_LAST_COMMIT

      COLOR=`hi_color`
      MINUTES_SINCE_LAST_COMMIT=`minutes_since_last_commit`

      if [ -n "$MINUTES_SINCE_LAST_COMMIT" ]; then
        local SINCE_LAST_COMMIT
        COLOR=`minutes_color MINUTES_SINCE_LAST_COMMIT`
        SINCE_LAST_COMMIT=" ${COLOR}$(minutes_since_last_commit)m${NORMAL}"
      fi
      # The __git_ps1 function inserts the current git branch where %s is
      local GIT_PROMPT
      GIT_PROMPT=`__git_ps1 "(${COLOR}%s$NORMAL)"`
      echo ${GIT_PROMPT}
    fi
  }

  # ℣ ℒ ∮ ֆ လ  ჶ Ꭶ ဝ ⬭ ⱇ ⬲
  # Build the prompt: {{{1
  build_prompt() {
    export PS1="╭-${BRIGHT_BLUE}\u${NORMAL}·${BRIGHT_BLUE}\W${NORMAL} \$(grb_git_prompt) ${NORMAL}\n╰ဝ "
    export PS2=" ❯ "
    export PS4=" + "
    }

    hi_color() {
      if [[ "$THEME" =~ dark ]]; then
        echo $WHITE
      else
        echo $BLACK
      fi
    }

  # Call the prompt function
  build_prompt
