#!/bin/sh

# ::::::::: Reload :::::::::::::::::::::::::::
alias SS=". ~/.bash_profile"

# ::::::::: Git ::::::::::::::::::::::::::::::
alias gst="git status"
alias gpr="git log origin/master.. --reverse"
alias gpt="git log origin/master.. --reverse --pretty='[\`%h\`](https://github.com/Handybook/handybook/commit/%H) %s'"
alias gpp="git log origin/master.. --reverse -p"
alias gpc="git log origin/master.. -- | wc -l"

# ::::::::: Vim ::::::::::::::::::::::::::::::
alias v=$NEOVIM
alias vi=v
alias view="v -MR"

# ::::::::: Tmux  ::::::::::::::::::::::::::::
alias t='tmux'
alias tls='tmux ls'
complete -F _tmux t

# ::::::::: Utils ::::::::::::::::::::::::::::
alias l="CLICOLOR_FORCE=1 ls -lAh"
alias lsa="CLICOLOR_FORCE=1 ls -A"
alias lsf="CLICOLOR_FORCE=1 ls -F"

alias lessr="less -R"

alias cp="cp -iv"
alias mv="mv -iv"

alias cls='printf "\033c"'

if command -v ggrep > /dev/null; then
  alias grep="ggrep --color"
else
  alias grep="grep --color"
fi

# ::::::::: GDB ::::::::::::::::::::::::::::::
alias gdb="gdb -quiet"

