#!/bin/sh

set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --show-toplevel`"  # repo's root dir
trap 'rm -rf "$dir/$$.gtags"' EXIT # delete temp directory upon EXIT

mkdir -p "$dir/$$.gtags"

# pipe project's files to gtags for tagging
# write to temp directory <pid>.gtags
git ls-files | \
  gtags --file - "$dir/$$.gtags"
mv "$dir/$$.gtags/"{GTAGS,GRTAGS,GPATH} "$dir"  # files: GTAGS GRTAGS GPATH

